name: prj_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  native_barcode_scanner: ^1.0.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  dio: ^5.4.0
  uuid: ^3.0.4
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  animations: ^2.0.8
  flutter_animate: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/
